set (CMAKE_C_COMPILER   "i386-elf-gcc")
set (CMAKE_LINKER       "i386-elf-ld")

set (CMAKE_ASM_LINK_EXECUTABLE "${CMAKE_LINKER} <LINK_FLAGS> <OBJECTS> -o <TARGET>")
set (CMAKE_C_LINK_EXECUTABLE   "${CMAKE_LINKER} <LINK_FLAGS> <OBJECTS> -o <TARGET>")
set (CMAKE_CXX_LINK_EXECUTABLE "${CMAKE_LINKER} <LINK_FLAGS> <OBJECTS> -o <TARGET>")
